/*
 * Created on 16 janv. 2018 ( Time 22:12:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dialogflow.bean.Client;
import com.dialogflow.bean.jpa.ClientEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class ClientServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public ClientServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'ClientEntity' to 'Client'
	 * @param clientEntity
	 */
	public Client mapClientEntityToClient(ClientEntity clientEntity) {
		if(clientEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Client client = map(clientEntity, Client.class);

		return client;
	}
	
	/**
	 * Mapping from 'Client' to 'ClientEntity'
	 * @param client
	 * @param clientEntity
	 */
	public void mapClientToClientEntity(Client client, ClientEntity clientEntity) {
		if(client == null) {
			return;
		}

		//--- Generic mapping 
		map(client, clientEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}