/*
 * Created on 16 janv. 2018 ( Time 22:40:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.web.common;

public interface ListItem {

	public String getValue();
	
	public String getLabel();
}
