/*
 * Created on 16 janv. 2018 ( Time 22:40:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Bien implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer refTranche;

    @Size( max = 100 )
    private String denomination;


    private Float supProv;


    private Float supFinale;

    @Size( max = 100 )
    private String tf;

    @Size( max = 100 )
    private String tfMere;

    @Size( max = 100 )
    private String etat;


    private Float prixHt;


    private Float prixTtc;


    private Date dateLivraison;

    @Size( max = 100 )
    private String ilot;

    @Size( max = 100 )
    private String tantieme;

    @Size( max = 100 )
    private String quotePart;


    private Date datePermisHabiter;


    private Float mntTva;


    private Float echMnt1;


    private Float echMnt2;


    private Float echMnt3;


    private Float echMnt4;


    private Integer echDelai1;


    private Integer echDelai2;


    private Integer echDelai3;


    private Integer echDelai4;

    @Size( max = 30 )
    private String typeBien;

    @Size( max = 30 )
    private String niveau;

    @Size( max = 30 )
    private String numBien;

    @Size( max = 30 )
    private String immeuble;

    @Size( max = 30 )
    private String orientation;


    private Float supBalcon;


    private Date dateCreation;


    private Date dateMaj;


    private Integer bienReference;


    private Float fraisDossier;

    @Size( max = 12 )
    private String livrable;


    private Date dateFacturation;

    @Size( max = 30 )
    private String numCadastrale;

    @Size( max = 30 )
    private String proprieteDite;


    private Float supInterieur;


    private Float supCouverte;

    @Size( max = 30 )
    private String stockFinal;


    private Date dateFactFinal;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefTranche( Integer refTranche ) {
        this.refTranche = refTranche;
    }
    public Integer getRefTranche() {
        return this.refTranche;
    }

    public void setDenomination( String denomination ) {
        this.denomination = denomination;
    }
    public String getDenomination() {
        return this.denomination;
    }

    public void setSupProv( Float supProv ) {
        this.supProv = supProv;
    }
    public Float getSupProv() {
        return this.supProv;
    }

    public void setSupFinale( Float supFinale ) {
        this.supFinale = supFinale;
    }
    public Float getSupFinale() {
        return this.supFinale;
    }

    public void setTf( String tf ) {
        this.tf = tf;
    }
    public String getTf() {
        return this.tf;
    }

    public void setTfMere( String tfMere ) {
        this.tfMere = tfMere;
    }
    public String getTfMere() {
        return this.tfMere;
    }

    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    public void setPrixHt( Float prixHt ) {
        this.prixHt = prixHt;
    }
    public Float getPrixHt() {
        return this.prixHt;
    }

    public void setPrixTtc( Float prixTtc ) {
        this.prixTtc = prixTtc;
    }
    public Float getPrixTtc() {
        return this.prixTtc;
    }

    public void setDateLivraison( Date dateLivraison ) {
        this.dateLivraison = dateLivraison;
    }
    public Date getDateLivraison() {
        return this.dateLivraison;
    }

    public void setIlot( String ilot ) {
        this.ilot = ilot;
    }
    public String getIlot() {
        return this.ilot;
    }

    public void setTantieme( String tantieme ) {
        this.tantieme = tantieme;
    }
    public String getTantieme() {
        return this.tantieme;
    }

    public void setQuotePart( String quotePart ) {
        this.quotePart = quotePart;
    }
    public String getQuotePart() {
        return this.quotePart;
    }

    public void setDatePermisHabiter( Date datePermisHabiter ) {
        this.datePermisHabiter = datePermisHabiter;
    }
    public Date getDatePermisHabiter() {
        return this.datePermisHabiter;
    }

    public void setMntTva( Float mntTva ) {
        this.mntTva = mntTva;
    }
    public Float getMntTva() {
        return this.mntTva;
    }

    public void setEchMnt1( Float echMnt1 ) {
        this.echMnt1 = echMnt1;
    }
    public Float getEchMnt1() {
        return this.echMnt1;
    }

    public void setEchMnt2( Float echMnt2 ) {
        this.echMnt2 = echMnt2;
    }
    public Float getEchMnt2() {
        return this.echMnt2;
    }

    public void setEchMnt3( Float echMnt3 ) {
        this.echMnt3 = echMnt3;
    }
    public Float getEchMnt3() {
        return this.echMnt3;
    }

    public void setEchMnt4( Float echMnt4 ) {
        this.echMnt4 = echMnt4;
    }
    public Float getEchMnt4() {
        return this.echMnt4;
    }

    public void setEchDelai1( Integer echDelai1 ) {
        this.echDelai1 = echDelai1;
    }
    public Integer getEchDelai1() {
        return this.echDelai1;
    }

    public void setEchDelai2( Integer echDelai2 ) {
        this.echDelai2 = echDelai2;
    }
    public Integer getEchDelai2() {
        return this.echDelai2;
    }

    public void setEchDelai3( Integer echDelai3 ) {
        this.echDelai3 = echDelai3;
    }
    public Integer getEchDelai3() {
        return this.echDelai3;
    }

    public void setEchDelai4( Integer echDelai4 ) {
        this.echDelai4 = echDelai4;
    }
    public Integer getEchDelai4() {
        return this.echDelai4;
    }

    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }
    public String getTypeBien() {
        return this.typeBien;
    }

    public void setNiveau( String niveau ) {
        this.niveau = niveau;
    }
    public String getNiveau() {
        return this.niveau;
    }

    public void setNumBien( String numBien ) {
        this.numBien = numBien;
    }
    public String getNumBien() {
        return this.numBien;
    }

    public void setImmeuble( String immeuble ) {
        this.immeuble = immeuble;
    }
    public String getImmeuble() {
        return this.immeuble;
    }

    public void setOrientation( String orientation ) {
        this.orientation = orientation;
    }
    public String getOrientation() {
        return this.orientation;
    }

    public void setSupBalcon( Float supBalcon ) {
        this.supBalcon = supBalcon;
    }
    public Float getSupBalcon() {
        return this.supBalcon;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    public void setBienReference( Integer bienReference ) {
        this.bienReference = bienReference;
    }
    public Integer getBienReference() {
        return this.bienReference;
    }

    public void setFraisDossier( Float fraisDossier ) {
        this.fraisDossier = fraisDossier;
    }
    public Float getFraisDossier() {
        return this.fraisDossier;
    }

    public void setLivrable( String livrable ) {
        this.livrable = livrable;
    }
    public String getLivrable() {
        return this.livrable;
    }

    public void setDateFacturation( Date dateFacturation ) {
        this.dateFacturation = dateFacturation;
    }
    public Date getDateFacturation() {
        return this.dateFacturation;
    }

    public void setNumCadastrale( String numCadastrale ) {
        this.numCadastrale = numCadastrale;
    }
    public String getNumCadastrale() {
        return this.numCadastrale;
    }

    public void setProprieteDite( String proprieteDite ) {
        this.proprieteDite = proprieteDite;
    }
    public String getProprieteDite() {
        return this.proprieteDite;
    }

    public void setSupInterieur( Float supInterieur ) {
        this.supInterieur = supInterieur;
    }
    public Float getSupInterieur() {
        return this.supInterieur;
    }

    public void setSupCouverte( Float supCouverte ) {
        this.supCouverte = supCouverte;
    }
    public Float getSupCouverte() {
        return this.supCouverte;
    }

    public void setStockFinal( String stockFinal ) {
        this.stockFinal = stockFinal;
    }
    public String getStockFinal() {
        return this.stockFinal;
    }

    public void setDateFactFinal( Date dateFactFinal ) {
        this.dateFactFinal = dateFactFinal;
    }
    public Date getDateFactFinal() {
        return this.dateFactFinal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refTranche);
        sb.append("|");
        sb.append(denomination);
        sb.append("|");
        sb.append(supProv);
        sb.append("|");
        sb.append(supFinale);
        sb.append("|");
        sb.append(tf);
        sb.append("|");
        sb.append(tfMere);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(prixHt);
        sb.append("|");
        sb.append(prixTtc);
        sb.append("|");
        sb.append(dateLivraison);
        sb.append("|");
        sb.append(ilot);
        sb.append("|");
        sb.append(tantieme);
        sb.append("|");
        sb.append(quotePart);
        sb.append("|");
        sb.append(datePermisHabiter);
        sb.append("|");
        sb.append(mntTva);
        sb.append("|");
        sb.append(echMnt1);
        sb.append("|");
        sb.append(echMnt2);
        sb.append("|");
        sb.append(echMnt3);
        sb.append("|");
        sb.append(echMnt4);
        sb.append("|");
        sb.append(echDelai1);
        sb.append("|");
        sb.append(echDelai2);
        sb.append("|");
        sb.append(echDelai3);
        sb.append("|");
        sb.append(echDelai4);
        sb.append("|");
        sb.append(typeBien);
        sb.append("|");
        sb.append(niveau);
        sb.append("|");
        sb.append(numBien);
        sb.append("|");
        sb.append(immeuble);
        sb.append("|");
        sb.append(orientation);
        sb.append("|");
        sb.append(supBalcon);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(bienReference);
        sb.append("|");
        sb.append(fraisDossier);
        sb.append("|");
        sb.append(livrable);
        sb.append("|");
        sb.append(dateFacturation);
        sb.append("|");
        sb.append(numCadastrale);
        sb.append("|");
        sb.append(proprieteDite);
        sb.append("|");
        sb.append(supInterieur);
        sb.append("|");
        sb.append(supCouverte);
        sb.append("|");
        sb.append(stockFinal);
        sb.append("|");
        sb.append(dateFactFinal);
        return sb.toString(); 
    } 


}
