/*
 * Created on 16 janv. 2018 ( Time 22:40:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class DossierClient implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer refClient;


    private Integer refDossier;


    private Integer quote;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefClient( Integer refClient ) {
        this.refClient = refClient;
    }
    public Integer getRefClient() {
        return this.refClient;
    }

    public void setRefDossier( Integer refDossier ) {
        this.refDossier = refDossier;
    }
    public Integer getRefDossier() {
        return this.refDossier;
    }

    public void setQuote( Integer quote ) {
        this.quote = quote;
    }
    public Integer getQuote() {
        return this.quote;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refClient);
        sb.append("|");
        sb.append(refDossier);
        sb.append("|");
        sb.append(quote);
        return sb.toString(); 
    } 


}
