/*
 * Created on 16 janv. 2018 ( Time 22:40:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Echeance implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer refDossier;


    private Integer numero;


    private Date dateEcheance;


    private Float montant;

    @Size( max = 500 )
    private String observation;


    private Float pourcentage;


    private Date dateCreation;


    private Date dateMaj;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefDossier( Integer refDossier ) {
        this.refDossier = refDossier;
    }
    public Integer getRefDossier() {
        return this.refDossier;
    }

    public void setNumero( Integer numero ) {
        this.numero = numero;
    }
    public Integer getNumero() {
        return this.numero;
    }

    public void setDateEcheance( Date dateEcheance ) {
        this.dateEcheance = dateEcheance;
    }
    public Date getDateEcheance() {
        return this.dateEcheance;
    }

    public void setMontant( Float montant ) {
        this.montant = montant;
    }
    public Float getMontant() {
        return this.montant;
    }

    public void setObservation( String observation ) {
        this.observation = observation;
    }
    public String getObservation() {
        return this.observation;
    }

    public void setPourcentage( Float pourcentage ) {
        this.pourcentage = pourcentage;
    }
    public Float getPourcentage() {
        return this.pourcentage;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refDossier);
        sb.append("|");
        sb.append(numero);
        sb.append("|");
        sb.append(dateEcheance);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(observation);
        sb.append("|");
        sb.append(pourcentage);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 


}
