/*
 * Created on 16 janv. 2018 ( Time 22:40:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Recette implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    private Integer refDossier;


    private Integer banque;


    private Float montant;


    private Date dateDepot;


    private Integer refVille;

    @Size( max = 100 )
    private String nomPayeur;

    @Size( max = 100 )
    private String numRecette;


    private Integer refModeRecette;

    @Size( max = 10 )
    private String etat;


    private Date dateCreation;


    private Date dateMaj;


    private Integer refEcheance;


    private Date dateVersement;

    @Size( max = 30 )
    private String cinPayeur;


    private Integer ordre;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setRefDossier( Integer refDossier ) {
        this.refDossier = refDossier;
    }
    public Integer getRefDossier() {
        return this.refDossier;
    }

    public void setBanque( Integer banque ) {
        this.banque = banque;
    }
    public Integer getBanque() {
        return this.banque;
    }

    public void setMontant( Float montant ) {
        this.montant = montant;
    }
    public Float getMontant() {
        return this.montant;
    }

    public void setDateDepot( Date dateDepot ) {
        this.dateDepot = dateDepot;
    }
    public Date getDateDepot() {
        return this.dateDepot;
    }

    public void setRefVille( Integer refVille ) {
        this.refVille = refVille;
    }
    public Integer getRefVille() {
        return this.refVille;
    }

    public void setNomPayeur( String nomPayeur ) {
        this.nomPayeur = nomPayeur;
    }
    public String getNomPayeur() {
        return this.nomPayeur;
    }

    public void setNumRecette( String numRecette ) {
        this.numRecette = numRecette;
    }
    public String getNumRecette() {
        return this.numRecette;
    }

    public void setRefModeRecette( Integer refModeRecette ) {
        this.refModeRecette = refModeRecette;
    }
    public Integer getRefModeRecette() {
        return this.refModeRecette;
    }

    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    public void setRefEcheance( Integer refEcheance ) {
        this.refEcheance = refEcheance;
    }
    public Integer getRefEcheance() {
        return this.refEcheance;
    }

    public void setDateVersement( Date dateVersement ) {
        this.dateVersement = dateVersement;
    }
    public Date getDateVersement() {
        return this.dateVersement;
    }

    public void setCinPayeur( String cinPayeur ) {
        this.cinPayeur = cinPayeur;
    }
    public String getCinPayeur() {
        return this.cinPayeur;
    }

    public void setOrdre( Integer ordre ) {
        this.ordre = ordre;
    }
    public Integer getOrdre() {
        return this.ordre;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(refDossier);
        sb.append("|");
        sb.append(banque);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(dateDepot);
        sb.append("|");
        sb.append(refVille);
        sb.append("|");
        sb.append(nomPayeur);
        sb.append("|");
        sb.append(numRecette);
        sb.append("|");
        sb.append(refModeRecette);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(refEcheance);
        sb.append("|");
        sb.append(dateVersement);
        sb.append("|");
        sb.append(cinPayeur);
        sb.append("|");
        sb.append(ordre);
        return sb.toString(); 
    } 


}
