/*
 * Created on 16 janv. 2018 ( Time 22:12:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.dialogflow.bean.ReferenceType;
import com.dialogflow.bean.jpa.ReferenceTypeEntity;
import com.dialogflow.business.service.ReferenceTypeService;
import com.dialogflow.business.service.mapping.ReferenceTypeServiceMapper;
import com.dialogflow.data.repository.jpa.ReferenceTypeJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of ReferenceTypeService
 */
@Component
@Transactional
public class ReferenceTypeServiceImpl implements ReferenceTypeService {

	@Resource
	private ReferenceTypeJpaRepository referenceTypeJpaRepository;

	@Resource
	private ReferenceTypeServiceMapper referenceTypeServiceMapper;
	
	@Override
	public ReferenceType findById(Integer id) {
		ReferenceTypeEntity referenceTypeEntity = referenceTypeJpaRepository.findOne(id);
		return referenceTypeServiceMapper.mapReferenceTypeEntityToReferenceType(referenceTypeEntity);
	}

	@Override
	public List<ReferenceType> findAll() {
		Iterable<ReferenceTypeEntity> entities = referenceTypeJpaRepository.findAll();
		List<ReferenceType> beans = new ArrayList<ReferenceType>();
		for(ReferenceTypeEntity referenceTypeEntity : entities) {
			beans.add(referenceTypeServiceMapper.mapReferenceTypeEntityToReferenceType(referenceTypeEntity));
		}
		return beans;
	}

	@Override
	public ReferenceType save(ReferenceType referenceType) {
		return update(referenceType) ;
	}

	@Override
	public ReferenceType create(ReferenceType referenceType) {
		ReferenceTypeEntity referenceTypeEntity = referenceTypeJpaRepository.findOne(referenceType.getId());
		if( referenceTypeEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		referenceTypeEntity = new ReferenceTypeEntity();
		referenceTypeServiceMapper.mapReferenceTypeToReferenceTypeEntity(referenceType, referenceTypeEntity);
		ReferenceTypeEntity referenceTypeEntitySaved = referenceTypeJpaRepository.save(referenceTypeEntity);
		return referenceTypeServiceMapper.mapReferenceTypeEntityToReferenceType(referenceTypeEntitySaved);
	}

	@Override
	public ReferenceType update(ReferenceType referenceType) {
		ReferenceTypeEntity referenceTypeEntity = referenceTypeJpaRepository.findOne(referenceType.getId());
		referenceTypeServiceMapper.mapReferenceTypeToReferenceTypeEntity(referenceType, referenceTypeEntity);
		ReferenceTypeEntity referenceTypeEntitySaved = referenceTypeJpaRepository.save(referenceTypeEntity);
		return referenceTypeServiceMapper.mapReferenceTypeEntityToReferenceType(referenceTypeEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		referenceTypeJpaRepository.delete(id);
	}

	public ReferenceTypeJpaRepository getReferenceTypeJpaRepository() {
		return referenceTypeJpaRepository;
	}

	public void setReferenceTypeJpaRepository(ReferenceTypeJpaRepository referenceTypeJpaRepository) {
		this.referenceTypeJpaRepository = referenceTypeJpaRepository;
	}

	public ReferenceTypeServiceMapper getReferenceTypeServiceMapper() {
		return referenceTypeServiceMapper;
	}

	public void setReferenceTypeServiceMapper(ReferenceTypeServiceMapper referenceTypeServiceMapper) {
		this.referenceTypeServiceMapper = referenceTypeServiceMapper;
	}

}
