/*
 * Created on 16 janv. 2018 ( Time 22:12:15 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.dialogflow.bean.Utilisateur;
import com.dialogflow.bean.jpa.UtilisateurEntity;
import com.dialogflow.business.service.UtilisateurService;
import com.dialogflow.business.service.mapping.UtilisateurServiceMapper;
import com.dialogflow.data.repository.jpa.UtilisateurJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of UtilisateurService
 */
@Component
@Transactional
public class UtilisateurServiceImpl implements UtilisateurService {

	@Resource
	private UtilisateurJpaRepository utilisateurJpaRepository;

	@Resource
	private UtilisateurServiceMapper utilisateurServiceMapper;
	
	@Override
	public Utilisateur findById(Integer id) {
		UtilisateurEntity utilisateurEntity = utilisateurJpaRepository.findOne(id);
		return utilisateurServiceMapper.mapUtilisateurEntityToUtilisateur(utilisateurEntity);
	}

	@Override
	public List<Utilisateur> findAll() {
		Iterable<UtilisateurEntity> entities = utilisateurJpaRepository.findAll();
		List<Utilisateur> beans = new ArrayList<Utilisateur>();
		for(UtilisateurEntity utilisateurEntity : entities) {
			beans.add(utilisateurServiceMapper.mapUtilisateurEntityToUtilisateur(utilisateurEntity));
		}
		return beans;
	}

	@Override
	public Utilisateur save(Utilisateur utilisateur) {
		return update(utilisateur) ;
	}

	@Override
	public Utilisateur create(Utilisateur utilisateur) {
		UtilisateurEntity utilisateurEntity = utilisateurJpaRepository.findOne(utilisateur.getId());
		if( utilisateurEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		utilisateurEntity = new UtilisateurEntity();
		utilisateurServiceMapper.mapUtilisateurToUtilisateurEntity(utilisateur, utilisateurEntity);
		UtilisateurEntity utilisateurEntitySaved = utilisateurJpaRepository.save(utilisateurEntity);
		return utilisateurServiceMapper.mapUtilisateurEntityToUtilisateur(utilisateurEntitySaved);
	}

	@Override
	public Utilisateur update(Utilisateur utilisateur) {
		UtilisateurEntity utilisateurEntity = utilisateurJpaRepository.findOne(utilisateur.getId());
		utilisateurServiceMapper.mapUtilisateurToUtilisateurEntity(utilisateur, utilisateurEntity);
		UtilisateurEntity utilisateurEntitySaved = utilisateurJpaRepository.save(utilisateurEntity);
		return utilisateurServiceMapper.mapUtilisateurEntityToUtilisateur(utilisateurEntitySaved);
	}

	@Override
	public void delete(Integer id) {
		utilisateurJpaRepository.delete(id);
	}

	public UtilisateurJpaRepository getUtilisateurJpaRepository() {
		return utilisateurJpaRepository;
	}

	public void setUtilisateurJpaRepository(UtilisateurJpaRepository utilisateurJpaRepository) {
		this.utilisateurJpaRepository = utilisateurJpaRepository;
	}

	public UtilisateurServiceMapper getUtilisateurServiceMapper() {
		return utilisateurServiceMapper;
	}

	public void setUtilisateurServiceMapper(UtilisateurServiceMapper utilisateurServiceMapper) {
		this.utilisateurServiceMapper = utilisateurServiceMapper;
	}

}
