/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "BIEN"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="BIEN", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="BienEntity.countAll", query="SELECT COUNT(x) FROM BienEntity x" )
} )
public class BienEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="DENOMINATION", length=100)
    private String     denomination ;

    @Column(name="SUP_PROV")
    private Float      supProv      ;

    @Column(name="SUP_FINALE")
    private Float      supFinale    ;

    @Column(name="TF", length=100)
    private String     tf           ;

    @Column(name="TF_MERE", length=100)
    private String     tfMere       ;

    @Column(name="ETAT", length=100)
    private String     etat         ;

    @Column(name="PRIX_HT")
    private Float      prixHt       ;

    @Column(name="PRIX_TTC")
    private Float      prixTtc      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_LIVRAISON")
    private Date       dateLivraison ;

    @Column(name="ILOT", length=100)
    private String     ilot         ;

    @Column(name="TANTIEME", length=100)
    private String     tantieme     ;

    @Column(name="QUOTE_PART", length=100)
    private String     quotePart    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_PERMIS_HABITER")
    private Date       datePermisHabiter ;

    @Column(name="MNT_TVA")
    private Float      mntTva       ;

    @Column(name="ECH_MNT_1")
    private Float      echMnt1      ;

    @Column(name="ECH_MNT_2")
    private Float      echMnt2      ;

    @Column(name="ECH_MNT_3")
    private Float      echMnt3      ;

    @Column(name="ECH_MNT_4")
    private Float      echMnt4      ;

    @Column(name="ECH_DELAI_1")
    private Integer    echDelai1    ;

    @Column(name="ECH_DELAI_2")
    private Integer    echDelai2    ;

    @Column(name="ECH_DELAI_3")
    private Integer    echDelai3    ;

    @Column(name="ECH_DELAI_4")
    private Integer    echDelai4    ;

    @Column(name="TYPE_BIEN", length=30)
    private String     typeBien     ;

    @Column(name="NIVEAU", length=30)
    private String     niveau       ;

    @Column(name="NUM_BIEN", length=30)
    private String     numBien      ;

    @Column(name="IMMEUBLE", length=30)
    private String     immeuble     ;

    @Column(name="ORIENTATION", length=30)
    private String     orientation  ;

    @Column(name="SUP_BALCON")
    private Float      supBalcon    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

    @Column(name="FRAIS_DOSSIER")
    private Float      fraisDossier ;

    @Column(name="LIVRABLE", length=12)
    private String     livrable     ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FACTURATION")
    private Date       dateFacturation ;

    @Column(name="NUM_CADASTRALE", length=30)
    private String     numCadastrale ;

    @Column(name="PROPRIETE_DITE", length=30)
    private String     proprieteDite ;

    @Column(name="SUP_INTERIEUR")
    private Float      supInterieur ;

    @Column(name="SUP_COUVERTE")
    private Float      supCouverte  ;

    @Column(name="STOCK_FINAL", length=30)
    private String     stockFinal   ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FACT_FINAL")
    private Date       dateFactFinal ;

	// "refTranche" (column "REF_TRANCHE") is not defined by itself because used as FK in a link 
	// "bienReference" (column "BIEN_REFERENCE") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="BIEN_REFERENCE", referencedColumnName="ID")
    private ReferenceEntity reference   ;

    @ManyToOne
    @JoinColumn(name="REF_TRANCHE", referencedColumnName="ID")
    private TrancheEntity tranche     ;




    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public BienEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : DENOMINATION ( VARCHAR2 ) 
    public void setDenomination( String denomination ) {
        this.denomination = denomination;
    }
    public String getDenomination() {
        return this.denomination;
    }

    //--- DATABASE MAPPING : SUP_PROV ( NUMBER ) 
    public void setSupProv( Float supProv ) {
        this.supProv = supProv;
    }
    public Float getSupProv() {
        return this.supProv;
    }

    //--- DATABASE MAPPING : SUP_FINALE ( NUMBER ) 
    public void setSupFinale( Float supFinale ) {
        this.supFinale = supFinale;
    }
    public Float getSupFinale() {
        return this.supFinale;
    }

    //--- DATABASE MAPPING : TF ( VARCHAR2 ) 
    public void setTf( String tf ) {
        this.tf = tf;
    }
    public String getTf() {
        return this.tf;
    }

    //--- DATABASE MAPPING : TF_MERE ( VARCHAR2 ) 
    public void setTfMere( String tfMere ) {
        this.tfMere = tfMere;
    }
    public String getTfMere() {
        return this.tfMere;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : PRIX_HT ( NUMBER ) 
    public void setPrixHt( Float prixHt ) {
        this.prixHt = prixHt;
    }
    public Float getPrixHt() {
        return this.prixHt;
    }

    //--- DATABASE MAPPING : PRIX_TTC ( NUMBER ) 
    public void setPrixTtc( Float prixTtc ) {
        this.prixTtc = prixTtc;
    }
    public Float getPrixTtc() {
        return this.prixTtc;
    }

    //--- DATABASE MAPPING : DATE_LIVRAISON ( DATE ) 
    public void setDateLivraison( Date dateLivraison ) {
        this.dateLivraison = dateLivraison;
    }
    public Date getDateLivraison() {
        return this.dateLivraison;
    }

    //--- DATABASE MAPPING : ILOT ( VARCHAR2 ) 
    public void setIlot( String ilot ) {
        this.ilot = ilot;
    }
    public String getIlot() {
        return this.ilot;
    }

    //--- DATABASE MAPPING : TANTIEME ( VARCHAR2 ) 
    public void setTantieme( String tantieme ) {
        this.tantieme = tantieme;
    }
    public String getTantieme() {
        return this.tantieme;
    }

    //--- DATABASE MAPPING : QUOTE_PART ( VARCHAR2 ) 
    public void setQuotePart( String quotePart ) {
        this.quotePart = quotePart;
    }
    public String getQuotePart() {
        return this.quotePart;
    }

    //--- DATABASE MAPPING : DATE_PERMIS_HABITER ( DATE ) 
    public void setDatePermisHabiter( Date datePermisHabiter ) {
        this.datePermisHabiter = datePermisHabiter;
    }
    public Date getDatePermisHabiter() {
        return this.datePermisHabiter;
    }

    //--- DATABASE MAPPING : MNT_TVA ( NUMBER ) 
    public void setMntTva( Float mntTva ) {
        this.mntTva = mntTva;
    }
    public Float getMntTva() {
        return this.mntTva;
    }

    //--- DATABASE MAPPING : ECH_MNT_1 ( NUMBER ) 
    public void setEchMnt1( Float echMnt1 ) {
        this.echMnt1 = echMnt1;
    }
    public Float getEchMnt1() {
        return this.echMnt1;
    }

    //--- DATABASE MAPPING : ECH_MNT_2 ( NUMBER ) 
    public void setEchMnt2( Float echMnt2 ) {
        this.echMnt2 = echMnt2;
    }
    public Float getEchMnt2() {
        return this.echMnt2;
    }

    //--- DATABASE MAPPING : ECH_MNT_3 ( NUMBER ) 
    public void setEchMnt3( Float echMnt3 ) {
        this.echMnt3 = echMnt3;
    }
    public Float getEchMnt3() {
        return this.echMnt3;
    }

    //--- DATABASE MAPPING : ECH_MNT_4 ( NUMBER ) 
    public void setEchMnt4( Float echMnt4 ) {
        this.echMnt4 = echMnt4;
    }
    public Float getEchMnt4() {
        return this.echMnt4;
    }

    //--- DATABASE MAPPING : ECH_DELAI_1 ( NUMBER ) 
    public void setEchDelai1( Integer echDelai1 ) {
        this.echDelai1 = echDelai1;
    }
    public Integer getEchDelai1() {
        return this.echDelai1;
    }

    //--- DATABASE MAPPING : ECH_DELAI_2 ( NUMBER ) 
    public void setEchDelai2( Integer echDelai2 ) {
        this.echDelai2 = echDelai2;
    }
    public Integer getEchDelai2() {
        return this.echDelai2;
    }

    //--- DATABASE MAPPING : ECH_DELAI_3 ( NUMBER ) 
    public void setEchDelai3( Integer echDelai3 ) {
        this.echDelai3 = echDelai3;
    }
    public Integer getEchDelai3() {
        return this.echDelai3;
    }

    //--- DATABASE MAPPING : ECH_DELAI_4 ( NUMBER ) 
    public void setEchDelai4( Integer echDelai4 ) {
        this.echDelai4 = echDelai4;
    }
    public Integer getEchDelai4() {
        return this.echDelai4;
    }

    //--- DATABASE MAPPING : TYPE_BIEN ( VARCHAR2 ) 
    public void setTypeBien( String typeBien ) {
        this.typeBien = typeBien;
    }
    public String getTypeBien() {
        return this.typeBien;
    }

    //--- DATABASE MAPPING : NIVEAU ( VARCHAR2 ) 
    public void setNiveau( String niveau ) {
        this.niveau = niveau;
    }
    public String getNiveau() {
        return this.niveau;
    }

    //--- DATABASE MAPPING : NUM_BIEN ( VARCHAR2 ) 
    public void setNumBien( String numBien ) {
        this.numBien = numBien;
    }
    public String getNumBien() {
        return this.numBien;
    }

    //--- DATABASE MAPPING : IMMEUBLE ( VARCHAR2 ) 
    public void setImmeuble( String immeuble ) {
        this.immeuble = immeuble;
    }
    public String getImmeuble() {
        return this.immeuble;
    }

    //--- DATABASE MAPPING : ORIENTATION ( VARCHAR2 ) 
    public void setOrientation( String orientation ) {
        this.orientation = orientation;
    }
    public String getOrientation() {
        return this.orientation;
    }

    //--- DATABASE MAPPING : SUP_BALCON ( NUMBER ) 
    public void setSupBalcon( Float supBalcon ) {
        this.supBalcon = supBalcon;
    }
    public Float getSupBalcon() {
        return this.supBalcon;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    //--- DATABASE MAPPING : FRAIS_DOSSIER ( NUMBER ) 
    public void setFraisDossier( Float fraisDossier ) {
        this.fraisDossier = fraisDossier;
    }
    public Float getFraisDossier() {
        return this.fraisDossier;
    }

    //--- DATABASE MAPPING : LIVRABLE ( VARCHAR2 ) 
    public void setLivrable( String livrable ) {
        this.livrable = livrable;
    }
    public String getLivrable() {
        return this.livrable;
    }

    //--- DATABASE MAPPING : DATE_FACTURATION ( DATE ) 
    public void setDateFacturation( Date dateFacturation ) {
        this.dateFacturation = dateFacturation;
    }
    public Date getDateFacturation() {
        return this.dateFacturation;
    }

    //--- DATABASE MAPPING : NUM_CADASTRALE ( VARCHAR2 ) 
    public void setNumCadastrale( String numCadastrale ) {
        this.numCadastrale = numCadastrale;
    }
    public String getNumCadastrale() {
        return this.numCadastrale;
    }

    //--- DATABASE MAPPING : PROPRIETE_DITE ( VARCHAR2 ) 
    public void setProprieteDite( String proprieteDite ) {
        this.proprieteDite = proprieteDite;
    }
    public String getProprieteDite() {
        return this.proprieteDite;
    }

    //--- DATABASE MAPPING : SUP_INTERIEUR ( NUMBER ) 
    public void setSupInterieur( Float supInterieur ) {
        this.supInterieur = supInterieur;
    }
    public Float getSupInterieur() {
        return this.supInterieur;
    }

    //--- DATABASE MAPPING : SUP_COUVERTE ( NUMBER ) 
    public void setSupCouverte( Float supCouverte ) {
        this.supCouverte = supCouverte;
    }
    public Float getSupCouverte() {
        return this.supCouverte;
    }

    //--- DATABASE MAPPING : STOCK_FINAL ( VARCHAR2 ) 
    public void setStockFinal( String stockFinal ) {
        this.stockFinal = stockFinal;
    }
    public String getStockFinal() {
        return this.stockFinal;
    }

    //--- DATABASE MAPPING : DATE_FACT_FINAL ( DATE ) 
    public void setDateFactFinal( Date dateFactFinal ) {
        this.dateFactFinal = dateFactFinal;
    }
    public Date getDateFactFinal() {
        return this.dateFactFinal;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setReference( ReferenceEntity reference ) {
        this.reference = reference;
    }
    public ReferenceEntity getReference() {
        return this.reference;
    }

    public void setTranche( TrancheEntity tranche ) {
        this.tranche = tranche;
    }
    public TrancheEntity getTranche() {
        return this.tranche;
    }




    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(denomination);
        sb.append("|");
        sb.append(supProv);
        sb.append("|");
        sb.append(supFinale);
        sb.append("|");
        sb.append(tf);
        sb.append("|");
        sb.append(tfMere);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(prixHt);
        sb.append("|");
        sb.append(prixTtc);
        sb.append("|");
        sb.append(dateLivraison);
        sb.append("|");
        sb.append(ilot);
        sb.append("|");
        sb.append(tantieme);
        sb.append("|");
        sb.append(quotePart);
        sb.append("|");
        sb.append(datePermisHabiter);
        sb.append("|");
        sb.append(mntTva);
        sb.append("|");
        sb.append(echMnt1);
        sb.append("|");
        sb.append(echMnt2);
        sb.append("|");
        sb.append(echMnt3);
        sb.append("|");
        sb.append(echMnt4);
        sb.append("|");
        sb.append(echDelai1);
        sb.append("|");
        sb.append(echDelai2);
        sb.append("|");
        sb.append(echDelai3);
        sb.append("|");
        sb.append(echDelai4);
        sb.append("|");
        sb.append(typeBien);
        sb.append("|");
        sb.append(niveau);
        sb.append("|");
        sb.append(numBien);
        sb.append("|");
        sb.append(immeuble);
        sb.append("|");
        sb.append(orientation);
        sb.append("|");
        sb.append(supBalcon);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(fraisDossier);
        sb.append("|");
        sb.append(livrable);
        sb.append("|");
        sb.append(dateFacturation);
        sb.append("|");
        sb.append(numCadastrale);
        sb.append("|");
        sb.append(proprieteDite);
        sb.append("|");
        sb.append(supInterieur);
        sb.append("|");
        sb.append(supCouverte);
        sb.append("|");
        sb.append(stockFinal);
        sb.append("|");
        sb.append(dateFactFinal);
        return sb.toString(); 
    } 

}
