/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CLIENT"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CLIENT", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClientEntity.countAll", query="SELECT COUNT(x) FROM ClientEntity x" )
} )
public class ClientEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM_CLIENT", length=200)
    private String     nomClient    ;

    @Column(name="PRENOM_CLIENT", length=200)
    private String     prenomClient ;

    @Column(name="CIN_CLIENT", length=200)
    private String     cinClient    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_EXPIRATION")
    private Date       dateExpiration ;

    @Column(name="ADRESSE", length=200)
    private String     adresse      ;

    @Column(name="REF_PROFESSION")
    private Integer    refProfession ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_NAISSANCE")
    private Date       dateNaissance ;

    @Column(name="LIEU_NAISSANCE", length=30)
    private String     lieuNaissance ;

    @Column(name="REF_ETAT_CIVIL")
    private BigDecimal refEtatCivil ;

    @Column(name="TEL_1", length=100)
    private String     tel1         ;

    @Column(name="TEL_2", length=100)
    private String     tel2         ;

    @Column(name="REVENU")
    private Integer    revenu       ;

    @Column(name="EMAIL", length=100)
    private String     email        ;

    @Column(name="REF_NATIONALITE")
    private Integer    refNationalite ;

    @Column(name="REF_VILLE")
    private Integer    refVille     ;

    @Column(name="QUOTE")
    private Integer    quote        ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="client", targetEntity=DossierClientEntity.class)
    private List<DossierClientEntity> listOfDossierClient;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClientEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM_CLIENT ( VARCHAR2 ) 
    public void setNomClient( String nomClient ) {
        this.nomClient = nomClient;
    }
    public String getNomClient() {
        return this.nomClient;
    }

    //--- DATABASE MAPPING : PRENOM_CLIENT ( VARCHAR2 ) 
    public void setPrenomClient( String prenomClient ) {
        this.prenomClient = prenomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }

    //--- DATABASE MAPPING : CIN_CLIENT ( VARCHAR2 ) 
    public void setCinClient( String cinClient ) {
        this.cinClient = cinClient;
    }
    public String getCinClient() {
        return this.cinClient;
    }

    //--- DATABASE MAPPING : DATE_EXPIRATION ( DATE ) 
    public void setDateExpiration( Date dateExpiration ) {
        this.dateExpiration = dateExpiration;
    }
    public Date getDateExpiration() {
        return this.dateExpiration;
    }

    //--- DATABASE MAPPING : ADRESSE ( VARCHAR2 ) 
    public void setAdresse( String adresse ) {
        this.adresse = adresse;
    }
    public String getAdresse() {
        return this.adresse;
    }

    //--- DATABASE MAPPING : REF_PROFESSION ( NUMBER ) 
    public void setRefProfession( Integer refProfession ) {
        this.refProfession = refProfession;
    }
    public Integer getRefProfession() {
        return this.refProfession;
    }

    //--- DATABASE MAPPING : DATE_NAISSANCE ( DATE ) 
    public void setDateNaissance( Date dateNaissance ) {
        this.dateNaissance = dateNaissance;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }

    //--- DATABASE MAPPING : LIEU_NAISSANCE ( VARCHAR2 ) 
    public void setLieuNaissance( String lieuNaissance ) {
        this.lieuNaissance = lieuNaissance;
    }
    public String getLieuNaissance() {
        return this.lieuNaissance;
    }

    //--- DATABASE MAPPING : REF_ETAT_CIVIL ( NUMBER ) 
    public void setRefEtatCivil( BigDecimal refEtatCivil ) {
        this.refEtatCivil = refEtatCivil;
    }
    public BigDecimal getRefEtatCivil() {
        return this.refEtatCivil;
    }

    //--- DATABASE MAPPING : TEL_1 ( VARCHAR2 ) 
    public void setTel1( String tel1 ) {
        this.tel1 = tel1;
    }
    public String getTel1() {
        return this.tel1;
    }

    //--- DATABASE MAPPING : TEL_2 ( VARCHAR2 ) 
    public void setTel2( String tel2 ) {
        this.tel2 = tel2;
    }
    public String getTel2() {
        return this.tel2;
    }

    //--- DATABASE MAPPING : REVENU ( NUMBER ) 
    public void setRevenu( Integer revenu ) {
        this.revenu = revenu;
    }
    public Integer getRevenu() {
        return this.revenu;
    }

    //--- DATABASE MAPPING : EMAIL ( VARCHAR2 ) 
    public void setEmail( String email ) {
        this.email = email;
    }
    public String getEmail() {
        return this.email;
    }

    //--- DATABASE MAPPING : REF_NATIONALITE ( NUMBER ) 
    public void setRefNationalite( Integer refNationalite ) {
        this.refNationalite = refNationalite;
    }
    public Integer getRefNationalite() {
        return this.refNationalite;
    }

    //--- DATABASE MAPPING : REF_VILLE ( NUMBER ) 
    public void setRefVille( Integer refVille ) {
        this.refVille = refVille;
    }
    public Integer getRefVille() {
        return this.refVille;
    }

    //--- DATABASE MAPPING : QUOTE ( NUMBER ) 
    public void setQuote( Integer quote ) {
        this.quote = quote;
    }
    public Integer getQuote() {
        return this.quote;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfDossierClient( List<DossierClientEntity> listOfDossierClient ) {
        this.listOfDossierClient = listOfDossierClient;
    }
    public List<DossierClientEntity> getListOfDossierClient() {
        return this.listOfDossierClient;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nomClient);
        sb.append("|");
        sb.append(prenomClient);
        sb.append("|");
        sb.append(cinClient);
        sb.append("|");
        sb.append(dateExpiration);
        sb.append("|");
        sb.append(adresse);
        sb.append("|");
        sb.append(refProfession);
        sb.append("|");
        sb.append(dateNaissance);
        sb.append("|");
        sb.append(lieuNaissance);
        sb.append("|");
        sb.append(refEtatCivil);
        sb.append("|");
        sb.append(tel1);
        sb.append("|");
        sb.append(tel2);
        sb.append("|");
        sb.append(revenu);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(refNationalite);
        sb.append("|");
        sb.append(refVille);
        sb.append("|");
        sb.append(quote);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
