/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "DOSSIER_CREDIT"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="DOSSIER_CREDIT", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DossierCreditEntity.countAll", query="SELECT COUNT(x) FROM DossierCreditEntity x" )
} )
public class DossierCreditEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="REF_BANQUE")
    private Integer    refBanque    ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEPOT_CREDIT")
    private Date       dateDepotCredit ;

    @Column(name="MONTANT_CREDIT_DEMANDE")
    private Float      montantCreditDemande ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEBLOC_CREDIT")
    private Date       dateDeblocCredit ;

    @Column(name="MONTANT_CREDIT_DEBLOC")
    private Float      montantCreditDebloc ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

	// "refDossier" (column "REF_DOSSIER") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="REF_DOSSIER", referencedColumnName="ID")
    private DossierEntity dossier     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DossierCreditEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : REF_BANQUE ( NUMBER ) 
    public void setRefBanque( Integer refBanque ) {
        this.refBanque = refBanque;
    }
    public Integer getRefBanque() {
        return this.refBanque;
    }

    //--- DATABASE MAPPING : DATE_DEPOT_CREDIT ( DATE ) 
    public void setDateDepotCredit( Date dateDepotCredit ) {
        this.dateDepotCredit = dateDepotCredit;
    }
    public Date getDateDepotCredit() {
        return this.dateDepotCredit;
    }

    //--- DATABASE MAPPING : MONTANT_CREDIT_DEMANDE ( NUMBER ) 
    public void setMontantCreditDemande( Float montantCreditDemande ) {
        this.montantCreditDemande = montantCreditDemande;
    }
    public Float getMontantCreditDemande() {
        return this.montantCreditDemande;
    }

    //--- DATABASE MAPPING : DATE_DEBLOC_CREDIT ( DATE ) 
    public void setDateDeblocCredit( Date dateDeblocCredit ) {
        this.dateDeblocCredit = dateDeblocCredit;
    }
    public Date getDateDeblocCredit() {
        return this.dateDeblocCredit;
    }

    //--- DATABASE MAPPING : MONTANT_CREDIT_DEBLOC ( NUMBER ) 
    public void setMontantCreditDebloc( Float montantCreditDebloc ) {
        this.montantCreditDebloc = montantCreditDebloc;
    }
    public Float getMontantCreditDebloc() {
        return this.montantCreditDebloc;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDossier( DossierEntity dossier ) {
        this.dossier = dossier;
    }
    public DossierEntity getDossier() {
        return this.dossier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(refBanque);
        sb.append("|");
        sb.append(dateDepotCredit);
        sb.append("|");
        sb.append(montantCreditDemande);
        sb.append("|");
        sb.append(dateDeblocCredit);
        sb.append("|");
        sb.append(montantCreditDebloc);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
