/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "DOSSIER"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="DOSSIER", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DossierEntity.countAll", query="SELECT COUNT(x) FROM DossierEntity x" )
} )
public class DossierEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="REF_BIEN")
    private Integer    refBien      ;

    @Column(name="COMMERCIAL", length=100)
    private String     commercial   ;

    @Column(name="ETAT", length=100)
    private String     etat         ;

    @Column(name="REF_PROJET")
    private Integer    refProjet    ;

    @Column(name="REF_TRANCHE")
    private Integer    refTranche   ;

    @Column(name="TYPE_DESISTEMENT")
    private Integer    typeDesistement ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DESISTEMENT")
    private Date       dateDesistement ;

    @Column(name="NUM_DOSS_DOC", length=100)
    private String     numDossDoc   ;

    @Column(name="REF_CONVENTION")
    private Integer    refConvention ;

    @Column(name="NUM_VENTE_PROJET")
    private Long       numVenteProjet ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FACTURATION")
    private Date       dateFacturation ;

    @Column(name="FRAIS_DOSSIER")
    private Float      fraisDossier ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ACTE_LEGALISE")
    private Date       dateActeLegalise ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ACTE_ENVOYE")
    private Date       dateActeEnvoye ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ACTE_SIGNE")
    private Date       dateActeSigne ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ACTE_REMIS")
    private Date       dateActeRemis ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_FRAIS_DOSSIER")
    private Date       dateFraisDossier ;

    @Column(name="REF_TYPE_RECOUVREMENT")
    private Integer    refTypeRecouvrement ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_COMP_SIGN_CLI")
    private Date       dateCompSignCli ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_COMP_SIGN_PROM")
    private Date       dateCompSignProm ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_REMIS_COMP_CLI")
    private Date       dateRemisCompCli ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CONT_SIGN_CLI")
    private Date       dateContSignCli ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CONT_SIGN_PROM")
    private Date       dateContSignProm ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_REMIS_CLE")
    private Date       dateRemisCle ;

    @Column(name="OBSERVATION", length=500)
    private String     observation  ;

    @Column(name="REF_NOTAIRE")
    private Integer    refNotaire   ;

    @Temporal(TemporalType.DATE)
    @Column(name="DOSSIER_ENVOYE")
    private Date       dossierEnvoye ;

    @Column(name="SYNDIC_MNT")
    private Long       syndicMnt    ;

    @Temporal(TemporalType.DATE)
    @Column(name="SYNDIC_DATE")
    private Date       syndicDate   ;

    @Temporal(TemporalType.DATE)
    @Column(name="DOSSIER_ENVOYER")
    private Date       dossierEnvoyer ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="dossier", targetEntity=DossierCreditEntity.class)
    private List<DossierCreditEntity> listOfDossierCredit;

    @OneToMany(mappedBy="dossier", targetEntity=RecetteEntity.class)
    private List<RecetteEntity> listOfRecette;

    @OneToMany(mappedBy="dossier", targetEntity=DossierClientEntity.class)
    private List<DossierClientEntity> listOfDossierClient;

    @OneToMany(mappedBy="dossier", targetEntity=EcheanceEntity.class)
    private List<EcheanceEntity> listOfEcheance;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DossierEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : REF_BIEN ( NUMBER ) 
    public void setRefBien( Integer refBien ) {
        this.refBien = refBien;
    }
    public Integer getRefBien() {
        return this.refBien;
    }

    //--- DATABASE MAPPING : COMMERCIAL ( VARCHAR2 ) 
    public void setCommercial( String commercial ) {
        this.commercial = commercial;
    }
    public String getCommercial() {
        return this.commercial;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : REF_PROJET ( NUMBER ) 
    public void setRefProjet( Integer refProjet ) {
        this.refProjet = refProjet;
    }
    public Integer getRefProjet() {
        return this.refProjet;
    }

    //--- DATABASE MAPPING : REF_TRANCHE ( NUMBER ) 
    public void setRefTranche( Integer refTranche ) {
        this.refTranche = refTranche;
    }
    public Integer getRefTranche() {
        return this.refTranche;
    }

    //--- DATABASE MAPPING : TYPE_DESISTEMENT ( NUMBER ) 
    public void setTypeDesistement( Integer typeDesistement ) {
        this.typeDesistement = typeDesistement;
    }
    public Integer getTypeDesistement() {
        return this.typeDesistement;
    }

    //--- DATABASE MAPPING : DATE_DESISTEMENT ( DATE ) 
    public void setDateDesistement( Date dateDesistement ) {
        this.dateDesistement = dateDesistement;
    }
    public Date getDateDesistement() {
        return this.dateDesistement;
    }

    //--- DATABASE MAPPING : NUM_DOSS_DOC ( VARCHAR2 ) 
    public void setNumDossDoc( String numDossDoc ) {
        this.numDossDoc = numDossDoc;
    }
    public String getNumDossDoc() {
        return this.numDossDoc;
    }

    //--- DATABASE MAPPING : REF_CONVENTION ( NUMBER ) 
    public void setRefConvention( Integer refConvention ) {
        this.refConvention = refConvention;
    }
    public Integer getRefConvention() {
        return this.refConvention;
    }

    //--- DATABASE MAPPING : NUM_VENTE_PROJET ( NUMBER ) 
    public void setNumVenteProjet( Long numVenteProjet ) {
        this.numVenteProjet = numVenteProjet;
    }
    public Long getNumVenteProjet() {
        return this.numVenteProjet;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    //--- DATABASE MAPPING : DATE_FACTURATION ( DATE ) 
    public void setDateFacturation( Date dateFacturation ) {
        this.dateFacturation = dateFacturation;
    }
    public Date getDateFacturation() {
        return this.dateFacturation;
    }

    //--- DATABASE MAPPING : FRAIS_DOSSIER ( NUMBER ) 
    public void setFraisDossier( Float fraisDossier ) {
        this.fraisDossier = fraisDossier;
    }
    public Float getFraisDossier() {
        return this.fraisDossier;
    }

    //--- DATABASE MAPPING : DATE_ACTE_LEGALISE ( DATE ) 
    public void setDateActeLegalise( Date dateActeLegalise ) {
        this.dateActeLegalise = dateActeLegalise;
    }
    public Date getDateActeLegalise() {
        return this.dateActeLegalise;
    }

    //--- DATABASE MAPPING : DATE_ACTE_ENVOYE ( DATE ) 
    public void setDateActeEnvoye( Date dateActeEnvoye ) {
        this.dateActeEnvoye = dateActeEnvoye;
    }
    public Date getDateActeEnvoye() {
        return this.dateActeEnvoye;
    }

    //--- DATABASE MAPPING : DATE_ACTE_SIGNE ( DATE ) 
    public void setDateActeSigne( Date dateActeSigne ) {
        this.dateActeSigne = dateActeSigne;
    }
    public Date getDateActeSigne() {
        return this.dateActeSigne;
    }

    //--- DATABASE MAPPING : DATE_ACTE_REMIS ( DATE ) 
    public void setDateActeRemis( Date dateActeRemis ) {
        this.dateActeRemis = dateActeRemis;
    }
    public Date getDateActeRemis() {
        return this.dateActeRemis;
    }

    //--- DATABASE MAPPING : DATE_FRAIS_DOSSIER ( DATE ) 
    public void setDateFraisDossier( Date dateFraisDossier ) {
        this.dateFraisDossier = dateFraisDossier;
    }
    public Date getDateFraisDossier() {
        return this.dateFraisDossier;
    }

    //--- DATABASE MAPPING : REF_TYPE_RECOUVREMENT ( NUMBER ) 
    public void setRefTypeRecouvrement( Integer refTypeRecouvrement ) {
        this.refTypeRecouvrement = refTypeRecouvrement;
    }
    public Integer getRefTypeRecouvrement() {
        return this.refTypeRecouvrement;
    }

    //--- DATABASE MAPPING : DATE_COMP_SIGN_CLI ( DATE ) 
    public void setDateCompSignCli( Date dateCompSignCli ) {
        this.dateCompSignCli = dateCompSignCli;
    }
    public Date getDateCompSignCli() {
        return this.dateCompSignCli;
    }

    //--- DATABASE MAPPING : DATE_COMP_SIGN_PROM ( DATE ) 
    public void setDateCompSignProm( Date dateCompSignProm ) {
        this.dateCompSignProm = dateCompSignProm;
    }
    public Date getDateCompSignProm() {
        return this.dateCompSignProm;
    }

    //--- DATABASE MAPPING : DATE_REMIS_COMP_CLI ( DATE ) 
    public void setDateRemisCompCli( Date dateRemisCompCli ) {
        this.dateRemisCompCli = dateRemisCompCli;
    }
    public Date getDateRemisCompCli() {
        return this.dateRemisCompCli;
    }

    //--- DATABASE MAPPING : DATE_CONT_SIGN_CLI ( DATE ) 
    public void setDateContSignCli( Date dateContSignCli ) {
        this.dateContSignCli = dateContSignCli;
    }
    public Date getDateContSignCli() {
        return this.dateContSignCli;
    }

    //--- DATABASE MAPPING : DATE_CONT_SIGN_PROM ( DATE ) 
    public void setDateContSignProm( Date dateContSignProm ) {
        this.dateContSignProm = dateContSignProm;
    }
    public Date getDateContSignProm() {
        return this.dateContSignProm;
    }

    //--- DATABASE MAPPING : DATE_REMIS_CLE ( DATE ) 
    public void setDateRemisCle( Date dateRemisCle ) {
        this.dateRemisCle = dateRemisCle;
    }
    public Date getDateRemisCle() {
        return this.dateRemisCle;
    }

    //--- DATABASE MAPPING : OBSERVATION ( VARCHAR2 ) 
    public void setObservation( String observation ) {
        this.observation = observation;
    }
    public String getObservation() {
        return this.observation;
    }

    //--- DATABASE MAPPING : REF_NOTAIRE ( NUMBER ) 
    public void setRefNotaire( Integer refNotaire ) {
        this.refNotaire = refNotaire;
    }
    public Integer getRefNotaire() {
        return this.refNotaire;
    }

    //--- DATABASE MAPPING : DOSSIER_ENVOYE ( DATE ) 
    public void setDossierEnvoye( Date dossierEnvoye ) {
        this.dossierEnvoye = dossierEnvoye;
    }
    public Date getDossierEnvoye() {
        return this.dossierEnvoye;
    }

    //--- DATABASE MAPPING : SYNDIC_MNT ( NUMBER ) 
    public void setSyndicMnt( Long syndicMnt ) {
        this.syndicMnt = syndicMnt;
    }
    public Long getSyndicMnt() {
        return this.syndicMnt;
    }

    //--- DATABASE MAPPING : SYNDIC_DATE ( DATE ) 
    public void setSyndicDate( Date syndicDate ) {
        this.syndicDate = syndicDate;
    }
    public Date getSyndicDate() {
        return this.syndicDate;
    }

    //--- DATABASE MAPPING : DOSSIER_ENVOYER ( DATE ) 
    public void setDossierEnvoyer( Date dossierEnvoyer ) {
        this.dossierEnvoyer = dossierEnvoyer;
    }
    public Date getDossierEnvoyer() {
        return this.dossierEnvoyer;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfDossierCredit( List<DossierCreditEntity> listOfDossierCredit ) {
        this.listOfDossierCredit = listOfDossierCredit;
    }
    public List<DossierCreditEntity> getListOfDossierCredit() {
        return this.listOfDossierCredit;
    }

    public void setListOfRecette( List<RecetteEntity> listOfRecette ) {
        this.listOfRecette = listOfRecette;
    }
    public List<RecetteEntity> getListOfRecette() {
        return this.listOfRecette;
    }

    public void setListOfDossierClient( List<DossierClientEntity> listOfDossierClient ) {
        this.listOfDossierClient = listOfDossierClient;
    }
    public List<DossierClientEntity> getListOfDossierClient() {
        return this.listOfDossierClient;
    }

    public void setListOfEcheance( List<EcheanceEntity> listOfEcheance ) {
        this.listOfEcheance = listOfEcheance;
    }
    public List<EcheanceEntity> getListOfEcheance() {
        return this.listOfEcheance;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(refBien);
        sb.append("|");
        sb.append(commercial);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(refProjet);
        sb.append("|");
        sb.append(refTranche);
        sb.append("|");
        sb.append(typeDesistement);
        sb.append("|");
        sb.append(dateDesistement);
        sb.append("|");
        sb.append(numDossDoc);
        sb.append("|");
        sb.append(refConvention);
        sb.append("|");
        sb.append(numVenteProjet);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(dateFacturation);
        sb.append("|");
        sb.append(fraisDossier);
        sb.append("|");
        sb.append(dateActeLegalise);
        sb.append("|");
        sb.append(dateActeEnvoye);
        sb.append("|");
        sb.append(dateActeSigne);
        sb.append("|");
        sb.append(dateActeRemis);
        sb.append("|");
        sb.append(dateFraisDossier);
        sb.append("|");
        sb.append(refTypeRecouvrement);
        sb.append("|");
        sb.append(dateCompSignCli);
        sb.append("|");
        sb.append(dateCompSignProm);
        sb.append("|");
        sb.append(dateRemisCompCli);
        sb.append("|");
        sb.append(dateContSignCli);
        sb.append("|");
        sb.append(dateContSignProm);
        sb.append("|");
        sb.append(dateRemisCle);
        sb.append("|");
        sb.append(observation);
        sb.append("|");
        sb.append(refNotaire);
        sb.append("|");
        sb.append(dossierEnvoye);
        sb.append("|");
        sb.append(syndicMnt);
        sb.append("|");
        sb.append(syndicDate);
        sb.append("|");
        sb.append(dossierEnvoyer);
        return sb.toString(); 
    } 

}
