/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ECHEANCE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ECHEANCE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="EcheanceEntity.countAll", query="SELECT COUNT(x) FROM EcheanceEntity x" )
} )
public class EcheanceEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NUMERO")
    private Integer    numero       ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_ECHEANCE")
    private Date       dateEcheance ;

    @Column(name="MONTANT")
    private Float      montant      ;

    @Column(name="OBSERVATION", length=500)
    private String     observation  ;

    @Column(name="POURCENTAGE")
    private Float      pourcentage  ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

	// "refDossier" (column "REF_DOSSIER") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="REF_DOSSIER", referencedColumnName="ID")
    private DossierEntity dossier     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public EcheanceEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NUMERO ( NUMBER ) 
    public void setNumero( Integer numero ) {
        this.numero = numero;
    }
    public Integer getNumero() {
        return this.numero;
    }

    //--- DATABASE MAPPING : DATE_ECHEANCE ( DATE ) 
    public void setDateEcheance( Date dateEcheance ) {
        this.dateEcheance = dateEcheance;
    }
    public Date getDateEcheance() {
        return this.dateEcheance;
    }

    //--- DATABASE MAPPING : MONTANT ( NUMBER ) 
    public void setMontant( Float montant ) {
        this.montant = montant;
    }
    public Float getMontant() {
        return this.montant;
    }

    //--- DATABASE MAPPING : OBSERVATION ( VARCHAR2 ) 
    public void setObservation( String observation ) {
        this.observation = observation;
    }
    public String getObservation() {
        return this.observation;
    }

    //--- DATABASE MAPPING : POURCENTAGE ( NUMBER ) 
    public void setPourcentage( Float pourcentage ) {
        this.pourcentage = pourcentage;
    }
    public Float getPourcentage() {
        return this.pourcentage;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDossier( DossierEntity dossier ) {
        this.dossier = dossier;
    }
    public DossierEntity getDossier() {
        return this.dossier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(numero);
        sb.append("|");
        sb.append(dateEcheance);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(observation);
        sb.append("|");
        sb.append(pourcentage);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        return sb.toString(); 
    } 

}
