/*
 * Created on 16 janv. 2018 ( Time 22:11:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dialogflow.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "RECETTE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RECETTE", schema="USERIMMO" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="RecetteEntity.countAll", query="SELECT COUNT(x) FROM RecetteEntity x" )
} )
public class RecetteEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="BANQUE")
    private Integer    banque       ;

    @Column(name="MONTANT")
    private Float      montant      ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_DEPOT")
    private Date       dateDepot    ;

    @Column(name="REF_VILLE")
    private Integer    refVille     ;

    @Column(name="NOM_PAYEUR", length=100)
    private String     nomPayeur    ;

    @Column(name="NUM_RECETTE", length=100)
    private String     numRecette   ;

    @Column(name="REF_MODE_RECETTE")
    private Integer    refModeRecette ;

    @Column(name="ETAT", length=10)
    private String     etat         ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_CREATION")
    private Date       dateCreation ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_MAJ")
    private Date       dateMaj      ;

    @Column(name="REF_ECHEANCE")
    private Integer    refEcheance  ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE_VERSEMENT")
    private Date       dateVersement ;

    @Column(name="CIN_PAYEUR", length=30)
    private String     cinPayeur    ;

    @Column(name="ORDRE")
    private Integer    ordre        ;

	// "refDossier" (column "REF_DOSSIER") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="REF_DOSSIER", referencedColumnName="ID")
    private DossierEntity dossier     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RecetteEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : BANQUE ( NUMBER ) 
    public void setBanque( Integer banque ) {
        this.banque = banque;
    }
    public Integer getBanque() {
        return this.banque;
    }

    //--- DATABASE MAPPING : MONTANT ( NUMBER ) 
    public void setMontant( Float montant ) {
        this.montant = montant;
    }
    public Float getMontant() {
        return this.montant;
    }

    //--- DATABASE MAPPING : DATE_DEPOT ( DATE ) 
    public void setDateDepot( Date dateDepot ) {
        this.dateDepot = dateDepot;
    }
    public Date getDateDepot() {
        return this.dateDepot;
    }

    //--- DATABASE MAPPING : REF_VILLE ( NUMBER ) 
    public void setRefVille( Integer refVille ) {
        this.refVille = refVille;
    }
    public Integer getRefVille() {
        return this.refVille;
    }

    //--- DATABASE MAPPING : NOM_PAYEUR ( VARCHAR2 ) 
    public void setNomPayeur( String nomPayeur ) {
        this.nomPayeur = nomPayeur;
    }
    public String getNomPayeur() {
        return this.nomPayeur;
    }

    //--- DATABASE MAPPING : NUM_RECETTE ( VARCHAR2 ) 
    public void setNumRecette( String numRecette ) {
        this.numRecette = numRecette;
    }
    public String getNumRecette() {
        return this.numRecette;
    }

    //--- DATABASE MAPPING : REF_MODE_RECETTE ( NUMBER ) 
    public void setRefModeRecette( Integer refModeRecette ) {
        this.refModeRecette = refModeRecette;
    }
    public Integer getRefModeRecette() {
        return this.refModeRecette;
    }

    //--- DATABASE MAPPING : ETAT ( VARCHAR2 ) 
    public void setEtat( String etat ) {
        this.etat = etat;
    }
    public String getEtat() {
        return this.etat;
    }

    //--- DATABASE MAPPING : DATE_CREATION ( DATE ) 
    public void setDateCreation( Date dateCreation ) {
        this.dateCreation = dateCreation;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }

    //--- DATABASE MAPPING : DATE_MAJ ( DATE ) 
    public void setDateMaj( Date dateMaj ) {
        this.dateMaj = dateMaj;
    }
    public Date getDateMaj() {
        return this.dateMaj;
    }

    //--- DATABASE MAPPING : REF_ECHEANCE ( NUMBER ) 
    public void setRefEcheance( Integer refEcheance ) {
        this.refEcheance = refEcheance;
    }
    public Integer getRefEcheance() {
        return this.refEcheance;
    }

    //--- DATABASE MAPPING : DATE_VERSEMENT ( DATE ) 
    public void setDateVersement( Date dateVersement ) {
        this.dateVersement = dateVersement;
    }
    public Date getDateVersement() {
        return this.dateVersement;
    }

    //--- DATABASE MAPPING : CIN_PAYEUR ( VARCHAR2 ) 
    public void setCinPayeur( String cinPayeur ) {
        this.cinPayeur = cinPayeur;
    }
    public String getCinPayeur() {
        return this.cinPayeur;
    }

    //--- DATABASE MAPPING : ORDRE ( NUMBER ) 
    public void setOrdre( Integer ordre ) {
        this.ordre = ordre;
    }
    public Integer getOrdre() {
        return this.ordre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDossier( DossierEntity dossier ) {
        this.dossier = dossier;
    }
    public DossierEntity getDossier() {
        return this.dossier;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(banque);
        sb.append("|");
        sb.append(montant);
        sb.append("|");
        sb.append(dateDepot);
        sb.append("|");
        sb.append(refVille);
        sb.append("|");
        sb.append(nomPayeur);
        sb.append("|");
        sb.append(numRecette);
        sb.append("|");
        sb.append(refModeRecette);
        sb.append("|");
        sb.append(etat);
        sb.append("|");
        sb.append(dateCreation);
        sb.append("|");
        sb.append(dateMaj);
        sb.append("|");
        sb.append(refEcheance);
        sb.append("|");
        sb.append(dateVersement);
        sb.append("|");
        sb.append(cinPayeur);
        sb.append("|");
        sb.append(ordre);
        return sb.toString(); 
    } 

}
