/*
 * Created on 16 janv. 2018 ( Time 22:12:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dialogflow.bean.DossierClient;
import com.dialogflow.bean.jpa.DossierClientEntity;
import com.dialogflow.bean.jpa.ClientEntity;
import com.dialogflow.bean.jpa.DossierEntity;
import com.dialogflow.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class DossierClientServiceMapperTest {

	private DossierClientServiceMapper dossierClientServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		dossierClientServiceMapper = new DossierClientServiceMapper();
		dossierClientServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'DossierClientEntity' to 'DossierClient'
	 * @param dossierClientEntity
	 */
	@Test
	public void testMapDossierClientEntityToDossierClient() {
		// Given
		DossierClientEntity dossierClientEntity = new DossierClientEntity();
		dossierClientEntity.setQuote(mockValues.nextInteger());
		dossierClientEntity.setClient(new ClientEntity());
		dossierClientEntity.getClient().setId(mockValues.nextInteger());
		dossierClientEntity.setDossier(new DossierEntity());
		dossierClientEntity.getDossier().setId(mockValues.nextInteger());
		
		// When
		DossierClient dossierClient = dossierClientServiceMapper.mapDossierClientEntityToDossierClient(dossierClientEntity);
		
		// Then
		assertEquals(dossierClientEntity.getQuote(), dossierClient.getQuote());
		assertEquals(dossierClientEntity.getClient().getId(), dossierClient.getRefClient());
		assertEquals(dossierClientEntity.getDossier().getId(), dossierClient.getRefDossier());
	}
	
	/**
	 * Test : Mapping from 'DossierClient' to 'DossierClientEntity'
	 */
	@Test
	public void testMapDossierClientToDossierClientEntity() {
		// Given
		DossierClient dossierClient = new DossierClient();
		dossierClient.setQuote(mockValues.nextInteger());
		dossierClient.setRefClient(mockValues.nextInteger());
		dossierClient.setRefDossier(mockValues.nextInteger());

		DossierClientEntity dossierClientEntity = new DossierClientEntity();
		
		// When
		dossierClientServiceMapper.mapDossierClientToDossierClientEntity(dossierClient, dossierClientEntity);
		
		// Then
		assertEquals(dossierClient.getQuote(), dossierClientEntity.getQuote());
		assertEquals(dossierClient.getRefClient(), dossierClientEntity.getClient().getId());
		assertEquals(dossierClient.getRefDossier(), dossierClientEntity.getDossier().getId());
	}

}