/*
 * Created on 16 janv. 2018 ( Time 22:12:13 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dialogflow.bean.Dossier;
import com.dialogflow.bean.jpa.DossierEntity;
import com.dialogflow.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class DossierServiceMapperTest {

	private DossierServiceMapper dossierServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		dossierServiceMapper = new DossierServiceMapper();
		dossierServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'DossierEntity' to 'Dossier'
	 * @param dossierEntity
	 */
	@Test
	public void testMapDossierEntityToDossier() {
		// Given
		DossierEntity dossierEntity = new DossierEntity();
		dossierEntity.setRefBien(mockValues.nextInteger());
		dossierEntity.setCommercial(mockValues.nextString(100));
		dossierEntity.setEtat(mockValues.nextString(100));
		dossierEntity.setRefProjet(mockValues.nextInteger());
		dossierEntity.setRefTranche(mockValues.nextInteger());
		dossierEntity.setTypeDesistement(mockValues.nextInteger());
		dossierEntity.setDateDesistement(mockValues.nextDate());
		dossierEntity.setNumDossDoc(mockValues.nextString(100));
		dossierEntity.setRefConvention(mockValues.nextInteger());
		dossierEntity.setNumVenteProjet(mockValues.nextLong());
		dossierEntity.setDateCreation(mockValues.nextDate());
		dossierEntity.setDateMaj(mockValues.nextDate());
		dossierEntity.setDateFacturation(mockValues.nextDate());
		dossierEntity.setFraisDossier(mockValues.nextFloat());
		dossierEntity.setDateActeLegalise(mockValues.nextDate());
		dossierEntity.setDateActeEnvoye(mockValues.nextDate());
		dossierEntity.setDateActeSigne(mockValues.nextDate());
		dossierEntity.setDateActeRemis(mockValues.nextDate());
		dossierEntity.setDateFraisDossier(mockValues.nextDate());
		dossierEntity.setRefTypeRecouvrement(mockValues.nextInteger());
		dossierEntity.setDateCompSignCli(mockValues.nextDate());
		dossierEntity.setDateCompSignProm(mockValues.nextDate());
		dossierEntity.setDateRemisCompCli(mockValues.nextDate());
		dossierEntity.setDateContSignCli(mockValues.nextDate());
		dossierEntity.setDateContSignProm(mockValues.nextDate());
		dossierEntity.setDateRemisCle(mockValues.nextDate());
		dossierEntity.setObservation(mockValues.nextString(500));
		dossierEntity.setRefNotaire(mockValues.nextInteger());
		dossierEntity.setDossierEnvoye(mockValues.nextDate());
		dossierEntity.setSyndicMnt(mockValues.nextLong());
		dossierEntity.setSyndicDate(mockValues.nextDate());
		dossierEntity.setDossierEnvoyer(mockValues.nextDate());
		
		// When
		Dossier dossier = dossierServiceMapper.mapDossierEntityToDossier(dossierEntity);
		
		// Then
		assertEquals(dossierEntity.getRefBien(), dossier.getRefBien());
		assertEquals(dossierEntity.getCommercial(), dossier.getCommercial());
		assertEquals(dossierEntity.getEtat(), dossier.getEtat());
		assertEquals(dossierEntity.getRefProjet(), dossier.getRefProjet());
		assertEquals(dossierEntity.getRefTranche(), dossier.getRefTranche());
		assertEquals(dossierEntity.getTypeDesistement(), dossier.getTypeDesistement());
		assertEquals(dossierEntity.getDateDesistement(), dossier.getDateDesistement());
		assertEquals(dossierEntity.getNumDossDoc(), dossier.getNumDossDoc());
		assertEquals(dossierEntity.getRefConvention(), dossier.getRefConvention());
		assertEquals(dossierEntity.getNumVenteProjet(), dossier.getNumVenteProjet());
		assertEquals(dossierEntity.getDateCreation(), dossier.getDateCreation());
		assertEquals(dossierEntity.getDateMaj(), dossier.getDateMaj());
		assertEquals(dossierEntity.getDateFacturation(), dossier.getDateFacturation());
		assertEquals(dossierEntity.getFraisDossier(), dossier.getFraisDossier());
		assertEquals(dossierEntity.getDateActeLegalise(), dossier.getDateActeLegalise());
		assertEquals(dossierEntity.getDateActeEnvoye(), dossier.getDateActeEnvoye());
		assertEquals(dossierEntity.getDateActeSigne(), dossier.getDateActeSigne());
		assertEquals(dossierEntity.getDateActeRemis(), dossier.getDateActeRemis());
		assertEquals(dossierEntity.getDateFraisDossier(), dossier.getDateFraisDossier());
		assertEquals(dossierEntity.getRefTypeRecouvrement(), dossier.getRefTypeRecouvrement());
		assertEquals(dossierEntity.getDateCompSignCli(), dossier.getDateCompSignCli());
		assertEquals(dossierEntity.getDateCompSignProm(), dossier.getDateCompSignProm());
		assertEquals(dossierEntity.getDateRemisCompCli(), dossier.getDateRemisCompCli());
		assertEquals(dossierEntity.getDateContSignCli(), dossier.getDateContSignCli());
		assertEquals(dossierEntity.getDateContSignProm(), dossier.getDateContSignProm());
		assertEquals(dossierEntity.getDateRemisCle(), dossier.getDateRemisCle());
		assertEquals(dossierEntity.getObservation(), dossier.getObservation());
		assertEquals(dossierEntity.getRefNotaire(), dossier.getRefNotaire());
		assertEquals(dossierEntity.getDossierEnvoye(), dossier.getDossierEnvoye());
		assertEquals(dossierEntity.getSyndicMnt(), dossier.getSyndicMnt());
		assertEquals(dossierEntity.getSyndicDate(), dossier.getSyndicDate());
		assertEquals(dossierEntity.getDossierEnvoyer(), dossier.getDossierEnvoyer());
	}
	
	/**
	 * Test : Mapping from 'Dossier' to 'DossierEntity'
	 */
	@Test
	public void testMapDossierToDossierEntity() {
		// Given
		Dossier dossier = new Dossier();
		dossier.setRefBien(mockValues.nextInteger());
		dossier.setCommercial(mockValues.nextString(100));
		dossier.setEtat(mockValues.nextString(100));
		dossier.setRefProjet(mockValues.nextInteger());
		dossier.setRefTranche(mockValues.nextInteger());
		dossier.setTypeDesistement(mockValues.nextInteger());
		dossier.setDateDesistement(mockValues.nextDate());
		dossier.setNumDossDoc(mockValues.nextString(100));
		dossier.setRefConvention(mockValues.nextInteger());
		dossier.setNumVenteProjet(mockValues.nextLong());
		dossier.setDateCreation(mockValues.nextDate());
		dossier.setDateMaj(mockValues.nextDate());
		dossier.setDateFacturation(mockValues.nextDate());
		dossier.setFraisDossier(mockValues.nextFloat());
		dossier.setDateActeLegalise(mockValues.nextDate());
		dossier.setDateActeEnvoye(mockValues.nextDate());
		dossier.setDateActeSigne(mockValues.nextDate());
		dossier.setDateActeRemis(mockValues.nextDate());
		dossier.setDateFraisDossier(mockValues.nextDate());
		dossier.setRefTypeRecouvrement(mockValues.nextInteger());
		dossier.setDateCompSignCli(mockValues.nextDate());
		dossier.setDateCompSignProm(mockValues.nextDate());
		dossier.setDateRemisCompCli(mockValues.nextDate());
		dossier.setDateContSignCli(mockValues.nextDate());
		dossier.setDateContSignProm(mockValues.nextDate());
		dossier.setDateRemisCle(mockValues.nextDate());
		dossier.setObservation(mockValues.nextString(500));
		dossier.setRefNotaire(mockValues.nextInteger());
		dossier.setDossierEnvoye(mockValues.nextDate());
		dossier.setSyndicMnt(mockValues.nextLong());
		dossier.setSyndicDate(mockValues.nextDate());
		dossier.setDossierEnvoyer(mockValues.nextDate());

		DossierEntity dossierEntity = new DossierEntity();
		
		// When
		dossierServiceMapper.mapDossierToDossierEntity(dossier, dossierEntity);
		
		// Then
		assertEquals(dossier.getRefBien(), dossierEntity.getRefBien());
		assertEquals(dossier.getCommercial(), dossierEntity.getCommercial());
		assertEquals(dossier.getEtat(), dossierEntity.getEtat());
		assertEquals(dossier.getRefProjet(), dossierEntity.getRefProjet());
		assertEquals(dossier.getRefTranche(), dossierEntity.getRefTranche());
		assertEquals(dossier.getTypeDesistement(), dossierEntity.getTypeDesistement());
		assertEquals(dossier.getDateDesistement(), dossierEntity.getDateDesistement());
		assertEquals(dossier.getNumDossDoc(), dossierEntity.getNumDossDoc());
		assertEquals(dossier.getRefConvention(), dossierEntity.getRefConvention());
		assertEquals(dossier.getNumVenteProjet(), dossierEntity.getNumVenteProjet());
		assertEquals(dossier.getDateCreation(), dossierEntity.getDateCreation());
		assertEquals(dossier.getDateMaj(), dossierEntity.getDateMaj());
		assertEquals(dossier.getDateFacturation(), dossierEntity.getDateFacturation());
		assertEquals(dossier.getFraisDossier(), dossierEntity.getFraisDossier());
		assertEquals(dossier.getDateActeLegalise(), dossierEntity.getDateActeLegalise());
		assertEquals(dossier.getDateActeEnvoye(), dossierEntity.getDateActeEnvoye());
		assertEquals(dossier.getDateActeSigne(), dossierEntity.getDateActeSigne());
		assertEquals(dossier.getDateActeRemis(), dossierEntity.getDateActeRemis());
		assertEquals(dossier.getDateFraisDossier(), dossierEntity.getDateFraisDossier());
		assertEquals(dossier.getRefTypeRecouvrement(), dossierEntity.getRefTypeRecouvrement());
		assertEquals(dossier.getDateCompSignCli(), dossierEntity.getDateCompSignCli());
		assertEquals(dossier.getDateCompSignProm(), dossierEntity.getDateCompSignProm());
		assertEquals(dossier.getDateRemisCompCli(), dossierEntity.getDateRemisCompCli());
		assertEquals(dossier.getDateContSignCli(), dossierEntity.getDateContSignCli());
		assertEquals(dossier.getDateContSignProm(), dossierEntity.getDateContSignProm());
		assertEquals(dossier.getDateRemisCle(), dossierEntity.getDateRemisCle());
		assertEquals(dossier.getObservation(), dossierEntity.getObservation());
		assertEquals(dossier.getRefNotaire(), dossierEntity.getRefNotaire());
		assertEquals(dossier.getDossierEnvoye(), dossierEntity.getDossierEnvoye());
		assertEquals(dossier.getSyndicMnt(), dossierEntity.getSyndicMnt());
		assertEquals(dossier.getSyndicDate(), dossierEntity.getSyndicDate());
		assertEquals(dossier.getDossierEnvoyer(), dossierEntity.getDossierEnvoyer());
	}

}