/*
 * Created on 16 janv. 2018 ( Time 22:12:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dialogflow.bean.Profil;
import com.dialogflow.bean.jpa.ProfilEntity;
import com.dialogflow.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ProfilServiceMapperTest {

	private ProfilServiceMapper profilServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		profilServiceMapper = new ProfilServiceMapper();
		profilServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ProfilEntity' to 'Profil'
	 * @param profilEntity
	 */
	@Test
	public void testMapProfilEntityToProfil() {
		// Given
		ProfilEntity profilEntity = new ProfilEntity();
		profilEntity.setDescription(mockValues.nextString(100));
		profilEntity.setDateCreation(mockValues.nextDate());
		profilEntity.setDateMaj(mockValues.nextDate());
		
		// When
		Profil profil = profilServiceMapper.mapProfilEntityToProfil(profilEntity);
		
		// Then
		assertEquals(profilEntity.getDescription(), profil.getDescription());
		assertEquals(profilEntity.getDateCreation(), profil.getDateCreation());
		assertEquals(profilEntity.getDateMaj(), profil.getDateMaj());
	}
	
	/**
	 * Test : Mapping from 'Profil' to 'ProfilEntity'
	 */
	@Test
	public void testMapProfilToProfilEntity() {
		// Given
		Profil profil = new Profil();
		profil.setDescription(mockValues.nextString(100));
		profil.setDateCreation(mockValues.nextDate());
		profil.setDateMaj(mockValues.nextDate());

		ProfilEntity profilEntity = new ProfilEntity();
		
		// When
		profilServiceMapper.mapProfilToProfilEntity(profil, profilEntity);
		
		// Then
		assertEquals(profil.getDescription(), profilEntity.getDescription());
		assertEquals(profil.getDateCreation(), profilEntity.getDateCreation());
		assertEquals(profil.getDateMaj(), profilEntity.getDateMaj());
	}

}