/*
 * Created on 16 janv. 2018 ( Time 22:12:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dialogflow.bean.Projet;
import com.dialogflow.bean.jpa.ProjetEntity;
import com.dialogflow.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class ProjetServiceMapperTest {

	private ProjetServiceMapper projetServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		projetServiceMapper = new ProjetServiceMapper();
		projetServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'ProjetEntity' to 'Projet'
	 * @param projetEntity
	 */
	@Test
	public void testMapProjetEntityToProjet() {
		// Given
		ProjetEntity projetEntity = new ProjetEntity();
		projetEntity.setLibelle(mockValues.nextString(100));
		projetEntity.setDescription(mockValues.nextString(200));
		projetEntity.setVilleProjet(mockValues.nextInteger());
		projetEntity.setDateCreation(mockValues.nextDate());
		projetEntity.setDateMaj(mockValues.nextDate());
		projetEntity.setCodeProjet(mockValues.nextString(30));
		projetEntity.setSequenceProjet(mockValues.nextString(50));
		projetEntity.setSequenceVente(mockValues.nextString(200));
		
		// When
		Projet projet = projetServiceMapper.mapProjetEntityToProjet(projetEntity);
		
		// Then
		assertEquals(projetEntity.getLibelle(), projet.getLibelle());
		assertEquals(projetEntity.getDescription(), projet.getDescription());
		assertEquals(projetEntity.getVilleProjet(), projet.getVilleProjet());
		assertEquals(projetEntity.getDateCreation(), projet.getDateCreation());
		assertEquals(projetEntity.getDateMaj(), projet.getDateMaj());
		assertEquals(projetEntity.getCodeProjet(), projet.getCodeProjet());
		assertEquals(projetEntity.getSequenceProjet(), projet.getSequenceProjet());
		assertEquals(projetEntity.getSequenceVente(), projet.getSequenceVente());
	}
	
	/**
	 * Test : Mapping from 'Projet' to 'ProjetEntity'
	 */
	@Test
	public void testMapProjetToProjetEntity() {
		// Given
		Projet projet = new Projet();
		projet.setLibelle(mockValues.nextString(100));
		projet.setDescription(mockValues.nextString(200));
		projet.setVilleProjet(mockValues.nextInteger());
		projet.setDateCreation(mockValues.nextDate());
		projet.setDateMaj(mockValues.nextDate());
		projet.setCodeProjet(mockValues.nextString(30));
		projet.setSequenceProjet(mockValues.nextString(50));
		projet.setSequenceVente(mockValues.nextString(200));

		ProjetEntity projetEntity = new ProjetEntity();
		
		// When
		projetServiceMapper.mapProjetToProjetEntity(projet, projetEntity);
		
		// Then
		assertEquals(projet.getLibelle(), projetEntity.getLibelle());
		assertEquals(projet.getDescription(), projetEntity.getDescription());
		assertEquals(projet.getVilleProjet(), projetEntity.getVilleProjet());
		assertEquals(projet.getDateCreation(), projetEntity.getDateCreation());
		assertEquals(projet.getDateMaj(), projetEntity.getDateMaj());
		assertEquals(projet.getCodeProjet(), projetEntity.getCodeProjet());
		assertEquals(projet.getSequenceProjet(), projetEntity.getSequenceProjet());
		assertEquals(projet.getSequenceVente(), projetEntity.getSequenceVente());
	}

}