/*
 * Created on 16 janv. 2018 ( Time 22:40:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.dialogflow.bean.Bien;
import com.dialogflow.business.service.BienService;
import com.dialogflow.web.listitem.BienListItem;

/**
 * Spring MVC controller for 'Bien' management.
 */
@Controller
public class BienRestController {

	@Resource
	private BienService bienService;
	
	@RequestMapping( value="/items/bien",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<BienListItem> findAllAsListItems() {
		List<Bien> list = bienService.findAll();
		List<BienListItem> items = new LinkedList<BienListItem>();
		for ( Bien bien : list ) {
			items.add(new BienListItem( bien ) );
		}
		return items;
	}
	
	@RequestMapping( value="/bien",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Bien> findAll() {
		return bienService.findAll();
	}

	@RequestMapping( value="/bien/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Bien findOne(@PathVariable("id") Integer id) {
		return bienService.findById(id);
	}
	
	@RequestMapping( value="/bien",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Bien create(@RequestBody Bien bien) {
		return bienService.create(bien);
	}

	@RequestMapping( value="/bien/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Bien update(@PathVariable("id") Integer id, @RequestBody Bien bien) {
		return bienService.update(bien);
	}

	@RequestMapping( value="/bien/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		bienService.delete(id);
	}
	
	@RequestMapping( value="/stock/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Long CountLibreByProjet(@PathVariable("id") Long id) {
		return bienService.CountLibreByProjet(id);
	}
	
}
