/*
 * Created on 16 janv. 2018 ( Time 22:40:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.dialogflow.bean.Dossier;
import com.dialogflow.business.service.DossierService;
import com.dialogflow.web.listitem.DossierListItem;

/**
 * Spring MVC controller for 'Dossier' management.
 */
@Controller
public class DossierRestController {

	@Resource
	private DossierService dossierService;
	
	@RequestMapping( value="/items/dossier",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DossierListItem> findAllAsListItems() {
		List<Dossier> list = dossierService.findAll();
		List<DossierListItem> items = new LinkedList<DossierListItem>();
		for ( Dossier dossier : list ) {
			items.add(new DossierListItem( dossier ) );
		}
		return items;
	}
	
	@RequestMapping( value="/dossier",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Dossier> findAll() {
		return dossierService.findAll();
	}

	@RequestMapping( value="/dossier/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dossier findOne(@PathVariable("id") Integer id) {
		return dossierService.findById(id);
	}
	
	@RequestMapping( value="/dossier",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dossier create(@RequestBody Dossier dossier) {
		return dossierService.create(dossier);
	}

	@RequestMapping( value="/dossier/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dossier update(@PathVariable("id") Integer id, @RequestBody Dossier dossier) {
		return dossierService.update(dossier);
	}

	@RequestMapping( value="/dossier/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		dossierService.delete(id);
	}
	
}
