/*
 * Created on 16 janv. 2018 ( Time 22:40:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.dialogflow.bean.Recette;
import com.dialogflow.business.service.RecetteService;
import com.dialogflow.web.listitem.RecetteListItem;

/**
 * Spring MVC controller for 'Recette' management.
 */
@Controller
public class RecetteRestController {

	@Resource
	private RecetteService recetteService;
	
	@RequestMapping( value="/items/recette",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<RecetteListItem> findAllAsListItems() {
		List<Recette> list = recetteService.findAll();
		List<RecetteListItem> items = new LinkedList<RecetteListItem>();
		for ( Recette recette : list ) {
			items.add(new RecetteListItem( recette ) );
		}
		return items;
	}
	
	@RequestMapping( value="/recette",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Recette> findAll() {
		return recetteService.findAll();
	}

	@RequestMapping( value="/recette/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Recette findOne(@PathVariable("id") Integer id) {
		return recetteService.findById(id);
	}
	
	@RequestMapping( value="/recette",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Recette create(@RequestBody Recette recette) {
		return recetteService.create(recette);
	}

	@RequestMapping( value="/recette/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Recette update(@PathVariable("id") Integer id, @RequestBody Recette recette) {
		return recetteService.update(recette);
	}

	@RequestMapping( value="/recette/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		recetteService.delete(id);
	}
	
}
