/*
 * Created on 16 janv. 2018 ( Time 22:40:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.dialogflow.bean.Reference;
import com.dialogflow.business.service.ReferenceService;
import com.dialogflow.web.listitem.ReferenceListItem;

/**
 * Spring MVC controller for 'Reference' management.
 */
@Controller
public class ReferenceRestController {

	@Resource
	private ReferenceService referenceService;
	
	@RequestMapping( value="/items/reference",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<ReferenceListItem> findAllAsListItems() {
		List<Reference> list = referenceService.findAll();
		List<ReferenceListItem> items = new LinkedList<ReferenceListItem>();
		for ( Reference reference : list ) {
			items.add(new ReferenceListItem( reference ) );
		}
		return items;
	}
	
	@RequestMapping( value="/reference",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Reference> findAll() {
		return referenceService.findAll();
	}

	@RequestMapping( value="/reference/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Reference findOne(@PathVariable("id") Integer id) {
		return referenceService.findById(id);
	}
	
	@RequestMapping( value="/reference",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Reference create(@RequestBody Reference reference) {
		return referenceService.create(reference);
	}

	@RequestMapping( value="/reference/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Reference update(@PathVariable("id") Integer id, @RequestBody Reference reference) {
		return referenceService.update(reference);
	}

	@RequestMapping( value="/reference/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Integer id) {
		referenceService.delete(id);
	}
	
}
