/*
 * Created on 16 janv. 2018 ( Time 22:40:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service;

import java.util.List;

import com.dialogflow.bean.Dossier;
import com.dialogflow.object.VenteObject;

/**
 * Business Service Interface for entity Dossier.
 */
public interface DossierService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Dossier findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Dossier> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Dossier save(Dossier entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Dossier update(Dossier entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Dossier create(Dossier entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


	VenteObject ventesParProjet(Long projet);
}
