/*
 * Created on 16 janv. 2018 ( Time 22:40:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service;

import java.util.List;

import com.dialogflow.bean.DossierCredit;

/**
 * Business Service Interface for entity DossierCredit.
 */
public interface DossierCreditService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	DossierCredit findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<DossierCredit> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	DossierCredit save(DossierCredit entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	DossierCredit update(DossierCredit entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	DossierCredit create(DossierCredit entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
