/*
 * Created on 16 janv. 2018 ( Time 22:40:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service;

import java.util.List;

import com.dialogflow.bean.Echeance;

/**
 * Business Service Interface for entity Echeance.
 */
public interface EcheanceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Echeance findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Echeance> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Echeance save(Echeance entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Echeance update(Echeance entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Echeance create(Echeance entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
