/*
 * Created on 16 janv. 2018 ( Time 22:40:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service;

import java.util.List;

import com.dialogflow.bean.UtilisateurTranche;

/**
 * Business Service Interface for entity UtilisateurTranche.
 */
public interface UtilisateurTrancheService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UtilisateurTranche findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<UtilisateurTranche> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UtilisateurTranche save(UtilisateurTranche entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UtilisateurTranche update(UtilisateurTranche entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UtilisateurTranche create(UtilisateurTranche entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
