/*
 * Created on 16 janv. 2018 ( Time 22:40:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.business.service;

import java.util.List;

import com.dialogflow.bean.Utilisateur;

/**
 * Business Service Interface for entity Utilisateur.
 */
public interface UtilisateurService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Utilisateur findById( Integer id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Utilisateur> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Utilisateur save(Utilisateur entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Utilisateur update(Utilisateur entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Utilisateur create(Utilisateur entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );


}
