/*
 * Created on 16 janv. 2018 ( Time 22:40:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.web.listitem;

import com.dialogflow.bean.Bien;
import com.dialogflow.web.common.ListItem;

public class BienListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public BienListItem(Bien bien) {
		super();

		this.value = ""
			 + bien.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = bien.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
