/*
 * Created on 16 janv. 2018 ( Time 22:40:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.dialogflow.web.listitem;

import com.dialogflow.bean.Recette;
import com.dialogflow.web.common.ListItem;

public class RecetteListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public RecetteListItem(Recette recette) {
		super();

		this.value = ""
			 + recette.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = recette.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
